// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHYFziSCcD4nmaErsR_rPH5I3Yr_5NbMQ',
    appId: '1:687846099564:web:314b58d3f52bd285746649',
    messagingSenderId: '687846099564',
    projectId: 'habitstracker-b2415',
    authDomain: 'habitstracker-b2415.firebaseapp.com',
    storageBucket: 'habitstracker-b2415.firebasestorage.app',
    measurementId: 'G-3S9LKVHSTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6SzOG7eaZ9AD3en38hjYcw0wRppqOfzA',
    appId: '1:687846099564:android:2781e820f7490639746649',
    messagingSenderId: '687846099564',
    projectId: 'habitstracker-b2415',
    storageBucket: 'habitstracker-b2415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCniqnuDZ7KUXvSw4DEpRBPJ37BYYkQmXo',
    appId: '1:687846099564:ios:010b5be04244460c746649',
    messagingSenderId: '687846099564',
    projectId: 'habitstracker-b2415',
    storageBucket: 'habitstracker-b2415.firebasestorage.app',
    iosBundleId: 'com.example.habitstracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCniqnuDZ7KUXvSw4DEpRBPJ37BYYkQmXo',
    appId: '1:687846099564:ios:010b5be04244460c746649',
    messagingSenderId: '687846099564',
    projectId: 'habitstracker-b2415',
    storageBucket: 'habitstracker-b2415.firebasestorage.app',
    iosBundleId: 'com.example.habitstracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHYFziSCcD4nmaErsR_rPH5I3Yr_5NbMQ',
    appId: '1:687846099564:web:8a9b5b71e677f493746649',
    messagingSenderId: '687846099564',
    projectId: 'habitstracker-b2415',
    authDomain: 'habitstracker-b2415.firebaseapp.com',
    storageBucket: 'habitstracker-b2415.firebasestorage.app',
    measurementId: 'G-RDLPG9X285',
  );
}
